### PR TITLE
Use `he` for robust HTML entity encoding/decoding

### PR DESCRIPTION
**Pull request by mathiasbynens**
_ent_ has [several open issues](https://github.com/substack/node-ent/issues/created_by/mathiasbynens?state=open) that are not present in [_he_](http://mths.be/he).

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Ping @stagas

**Comment by mathiasbynens** [comment]
Why not?

**Comment by stagas** [comment]
The commit has activity out of scope, also it just replaces one lib that does a thing with another that does the same thing. I don't think anybody uses this project anyway or that it works at all.

**Comment by stagas** [comment]
In other words, abandoned, better leave as it is.

**Comment by mathiasbynens** [comment]
>  it just replaces one lib that does a thing with another that does the same thing

The difference is one of the libs is broken badly.

**Comment by stagas** [comment]
you have full access & npm ownership

**Pull request closed without merging**
